"""empty message

Revision ID: 2eb2a59b0e58
Revises: 363d9e4138f3
Create Date: 2019-03-25 01:28:38.464770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb2a59b0e58'
down_revision = '363d9e4138f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'last_read_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
